name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: [ self-hosted, gpu, cuda ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run model app
        run: python3 -m uvicorn main:model_app --host 0.0.0.0 --port 2222 --workers 4 --log-level debug
  build:
    runs-on: [ self-hosted, gpu, cuda ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
  test:
    needs: build
    runs-on: [ self-hosted, gpu, cuda ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test script
        run: pytest --maxfail=1